server:
  port: 9090
  servlet:
    context-path: /auth

spring:
  application.name: auth-server
  exposed:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/spring_kube_auth
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_SIZE:10}
  liquibase:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/spring_kube_auth
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    change-log: db/master.yml
  security:
    clients:
      - client-id: web
        client-secret: password

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: ${LOGGING_ROOT:error}
    io.lonmstalker: ${LOGGING_PROJECT:info}
    org:
      jdbc: ${LOGGING_SQL:error}
      jetbrains: ${LOGGING_SQL:error}

app:
  properties:
    auth:
      issuer: ${AUTH_ISSUER:http://localhost:9090}
      login-page: ${LOGIN_PAGE:/login}
      failure-url: ${FAILURE_URL:/failure}
      consent-page: ${CONSENT_PAGE:/consent}
      invite-link: ${INVITE_LINK:http://localhost:9090/auth/api/v1/reg/}
      blocked-time: ${BLOCKED_TIME:30}
    jwt:
      location: ${JWT_LOCATION:classpath:cert/keystore.jks}
      alias: ${JWT_ALIAS:auth-server}
      key-pass: ${JWT_KEY_PASS:changeit}
      key-store-pass: ${JWT_STORE_PATH:changeit}
    token:
      access-ttl: ${ACCESS_TTL:600}
      refresh-ttl: ${REFRESH_TTL:172800}
      create-refresh: ${ENABLED_REFRESH:true}
