server:
  port: 9090
  servlet:
    context-path: /auth

spring:
  application.name: auth-server
  exposed:
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/spring_kube_auth}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_SIZE:10}
  liquibase:
    url: jdbc:postgresql://${DB_URL:localhost:5432/spring_kube_auth}
    user: ${MIGRATION_DB_USER:postgres}
    password: ${MIGRATION_DB_PASSWORD:postgres}
    change-log: db/master.yml
  security:
    oauth2:
      client:
        provider:
          google:
            user-name-attribute: sub
            token-uri: ${GOOGLE_TOKEN_URI:https://www.googleapis.com/oauth2/v4/token}
            user-info-uri: ${GOOGLE_INFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI:https://accounts.google.com/o/oauth2/v2/auth}
          vk:
            token-uri: ${VK_TOKEN_URI:https://oauth.vk.com/access_token}
            user-info-uri: ${VK_USER_INFO_URI:https://api.vk.com/method/users.get}
            authorization-uri: ${VK_AUTHORIZATION_URI:https://oauth.vk.com/authorize}
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:logic}
            client-secret: ${GOOGLE_CLIENT_SECRET:logic}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:9090}/auth/login
            scope:
              - openid
              - email
              - profile
          vk:
            client-id: ${VK_CLIENT_ID:logic}
            client-secret: ${VK_CLIENT_SECRET:logic}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:9090}/auth/login
            scope:
              - email
              - phone_number

    clients:
      - client-id: ${WEB_CLEINT_ID:web}
        client-secret: ${WEB_CLIENT_PASSWORD:password}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    root: ${LOGGING_ROOT:error}
    io.lonmstalker: ${LOGGING_PROJECT:info}
    org:
      jdbc: ${LOGGING_SQL:error}
      jetbrains: ${LOGGING_SQL:error}

app:
  properties:
    auth:
      issuer: ${AUTH_ISSUER:http://localhost:9090}
      invite-link: ${INVITE_LINK:http://localhost:9090/auth/api/v1/reg/}
      blocked-time: ${BLOCKED_TIME:30}
      redirect-url: ${CODE_REDIRECT_URL:http://localhost:9090}
    jwt:
      location: ${JWT_LOCATION:classpath:cert/keystore.pfx}
      alias: ${JWT_ALIAS:auth-server}
      key-pass: ${JWT_KEY_PASS:changeit}
      key-store-pass: ${JWT_STORE_PATH:changeit}
    token:
      access-ttl: ${ACCESS_TTL:600}
      refresh-ttl: ${REFRESH_TTL:172800}
      create-refresh: ${ENABLED_REFRESH:true}
    cookie:
      access-jwt: ${ACCESS_JWT_COOKIE:accessJwt}
      refresh-jwt: ${REFRESH_JWT_COOKIE:refreshJwt}
      access-max-age: ${ACCESS_JWT_MAX_AGE:580}
      refresh-max-age: ${REFRESH_JWT_MAX_AGE:172500}
      domain: ${COOKIE_DOMAIN:127.0.0.1}

schedule:
  token.clear: ${TOKEN_CLEAR:0 0 0 * * *}